FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/python-311@sha256:ae0aa0e09d9e8fb585a019f0f1e7031d53b0def2bf1934291928b9b52aa465d5
WORKDIR /opt/app-root

RUN pip install sqlalchemy # somehow sqlalchemy[asyncio] is not sufficient
{dependencies}
RUN pip install --no-cache llama-stack==0.2.10
RUN mkdir -p /opt/app-root/.llama/providers.d /opt/app-root/.cache
COPY redhat-distribution/run.yaml /opt/app-root/run.yaml
COPY redhat-distribution/providers.d /opt/app-root/.llama/providers.d
ENTRYPOINT ["python", "-m", "llama_stack.distribution.server.server", "--config", "/opt/app-root/run.yaml"]
